# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_scrap.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1232, 773)
        Form.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.784091, y1:0.102, x2:0, y2:1, stop:0.232955 rgba(189, 44, 161, 255), stop:0.596591 rgba(28, 73, 236, 255))")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1231, 771))
        self.frame.setStyleSheet("background-color:red;\n"
"background-color: qlineargradient(spread:pad, x1:0.784091, y1:0.102, x2:0, y2:1, stop:0.232955 rgba(189, 44, 161, 255), stop:0.596591 rgba(28, 73, 236, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insideForm = QtWidgets.QFrame(self.frame)
        self.insideForm.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"border-radius:10px;\n"
"")
        self.insideForm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.insideForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.insideForm.setObjectName("insideForm")
        self.menuForm = QtWidgets.QFrame(self.insideForm)
        self.menuForm.setGeometry(QtCore.QRect(0, 0, 291, 757))
        self.menuForm.setMaximumSize(QtCore.QSize(300, 16777215))
        self.menuForm.setStyleSheet("background-color: rgb(60, 91, 158);\n"
"border-radius:10px;")
        self.menuForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuForm.setObjectName("menuForm")
        self.logo = QtWidgets.QLabel(self.menuForm)
        self.logo.setGeometry(QtCore.QRect(-140, -110, 561, 241))
        self.logo.setStyleSheet("image: url(:/logo/C:/Users/DELL/Downloads/image-removebg-preview.png);\n"
"background-color: none;")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.btnAlgoritm = QtWidgets.QPushButton(self.menuForm)
        self.btnAlgoritm.setGeometry(QtCore.QRect(80, 340, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnAlgoritm.setFont(font)
        self.btnAlgoritm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlgoritm.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"padding: 0.8em 1.5em;\n"
"border-radius:2px;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 5px;\n"
"border:2px solid rgb(55, 75, 108);\n"
"font-weight:bold;\n"
"")
        self.btnAlgoritm.setObjectName("btnAlgoritm")
        self.btnScrapping = QtWidgets.QPushButton(self.menuForm)
        self.btnScrapping.setGeometry(QtCore.QRect(80, 220, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnScrapping.setFont(font)
        self.btnScrapping.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnScrapping.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"padding: 0.8em 1.5em;\n"
"border-radius:2px;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 5px;\n"
"border:2px solid rgb(55, 75, 108);\n"
"font-weight:bold;")
        self.btnScrapping.setObjectName("btnScrapping")
        self.btnProduct = QtWidgets.QPushButton(self.menuForm)
        self.btnProduct.setGeometry(QtCore.QRect(80, 280, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnProduct.setFont(font)
        self.btnProduct.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnProduct.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"padding: 0.8em 1.5em;\n"
"border-radius:2px;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 5px;\n"
"border:2px solid rgb(55, 75, 108);\n"
"font-weight:bold;\n"
"")
        self.btnProduct.setObjectName("btnProduct")
        self.btnDashboard = QtWidgets.QPushButton(self.menuForm)
        self.btnDashboard.setGeometry(QtCore.QRect(80, 160, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"padding: 0.8em 1.5em;\n"
"border-radius:2px;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 5px;\n"
"border:2px solid rgb(55, 75, 108);\n"
"font-weight:bold;")
        self.btnDashboard.setObjectName("btnDashboard")
        self.btnExit = QtWidgets.QPushButton(self.menuForm)
        self.btnExit.setGeometry(QtCore.QRect(80, 400, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnExit.setFont(font)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExit.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"padding: 0.8em 1.5em;\n"
"border-radius:2px;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 5px;\n"
"border:2px solid rgb(55, 75, 108);\n"
"font-weight:bold;")
        self.btnExit.setObjectName("btnExit")
        self.btnAlgoritm.raise_()
        self.btnScrapping.raise_()
        self.btnProduct.raise_()
        self.btnDashboard.raise_()
        self.btnExit.raise_()
        self.logo.raise_()
        self.label = QtWidgets.QLabel(self.insideForm)
        self.label.setGeometry(QtCore.QRect(530, 10, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(60, 91, 158);")
        self.label.setObjectName("label")
        self.btnStopScrap = QtWidgets.QPushButton(self.insideForm)
        self.btnStopScrap.setGeometry(QtCore.QRect(860, 610, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnStopScrap.setFont(font)
        self.btnStopScrap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStopScrap.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"border:2px solid rgb(55, 75, 108);\n"
"padding: 0.8em 1.5em;\n"
"border-radious:2px;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 10px;\n"
"align-item:center;\n"
"font-weight:bold;")
        self.btnStopScrap.setObjectName("btnStopScrap")
        self.pBar = QtWidgets.QProgressBar(self.insideForm)
        self.pBar.setGeometry(QtCore.QRect(420, 540, 701, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(15)
        self.pBar.setFont(font)
        self.pBar.setProperty("value", 50)
        self.pBar.setAlignment(QtCore.Qt.AlignCenter)
        self.pBar.setInvertedAppearance(False)
        self.pBar.setObjectName("pBar")
        self.btnStartScrap = QtWidgets.QPushButton(self.insideForm)
        self.btnStartScrap.setGeometry(QtCore.QRect(540, 600, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnStartScrap.setFont(font)
        self.btnStartScrap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStartScrap.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"border:2px solid rgb(55, 75, 108);\n"
"padding: 0.8em 1.5em;\n"
"border-radious:2px;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 10px;\n"
"align-item:center;\n"
"font-weight:bold;")
        self.btnStartScrap.setObjectName("btnStartScrap")
        self.tableWidget = QtWidgets.QTableWidget(self.insideForm)
        self.tableWidget.setGeometry(QtCore.QRect(325, 90, 841, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.insideForm)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnAlgoritm.setText(_translate("Form", "Algorithm"))
        self.btnScrapping.setText(_translate("Form", "Scrapping"))
        self.btnProduct.setText(_translate("Form", "Products"))
        self.btnDashboard.setText(_translate("Form", "Dashboard"))
        self.btnExit.setText(_translate("Form", "Exit"))
        self.label.setText(_translate("Form", "Scrapping"))
        self.btnStopScrap.setText(_translate("Form", "stop"))
        self.btnStartScrap.setText(_translate("Form", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
