# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_algo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1232, 773)
        Form.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.784091, y1:0.102, x2:0, y2:1, stop:0.232955 rgba(189, 44, 161, 255), stop:0.596591 rgba(28, 73, 236, 255))")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1231, 771))
        self.frame.setStyleSheet("background-color:red;\n"
"background-color: qlineargradient(spread:pad, x1:0.784091, y1:0.102, x2:0, y2:1, stop:0.232955 rgba(189, 44, 161, 255), stop:0.596591 rgba(28, 73, 236, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insideForm = QtWidgets.QFrame(self.frame)
        self.insideForm.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"border-radius:10px;\n"
"")
        self.insideForm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.insideForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.insideForm.setObjectName("insideForm")
        self.menuForm = QtWidgets.QFrame(self.insideForm)
        self.menuForm.setGeometry(QtCore.QRect(0, 0, 291, 757))
        self.menuForm.setMaximumSize(QtCore.QSize(300, 16777215))
        self.menuForm.setStyleSheet("background-color: rgb(60, 91, 158);\n"
"border-radius:10px;")
        self.menuForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuForm.setObjectName("menuForm")
        self.btnScrapping = QtWidgets.QPushButton(self.menuForm)
        self.btnScrapping.setGeometry(QtCore.QRect(80, 210, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnScrapping.setFont(font)
        self.btnScrapping.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnScrapping.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"border:2px solid rgb(55, 75, 108);\n"
"padding: 0.8em 1.5em;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 10px;\n"
"font-weight:bold;")
        self.btnScrapping.setObjectName("btnScrapping")
        self.logo = QtWidgets.QLabel(self.menuForm)
        self.logo.setGeometry(QtCore.QRect(-130, -50, 561, 241))
        self.logo.setStyleSheet("image: url(:/logo/C:/Users/DELL/Downloads/image-removebg-preview.png);\n"
"image: url(:/logo/C:/Users/amadi/Downloads/image-removebg-preview.png);\n"
"background-color: none;")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.btnProduct = QtWidgets.QPushButton(self.menuForm)
        self.btnProduct.setGeometry(QtCore.QRect(80, 270, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnProduct.setFont(font)
        self.btnProduct.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnProduct.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"border:2px solid rgb(55, 75, 108);\n"
"padding: 0.8em 1.5em;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 10px;\n"
"font-weight:bold;")
        self.btnProduct.setObjectName("btnProduct")
        self.btnAlgoritm = QtWidgets.QPushButton(self.menuForm)
        self.btnAlgoritm.setGeometry(QtCore.QRect(80, 330, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnAlgoritm.setFont(font)
        self.btnAlgoritm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlgoritm.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"border:2px solid rgb(55, 75, 108);\n"
"padding: 0.8em 1.5em;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 10px;\n"
"font-weight:bold;\n"
"")
        self.btnAlgoritm.setObjectName("btnAlgoritm")
        self.btnExit = QtWidgets.QPushButton(self.menuForm)
        self.btnExit.setGeometry(QtCore.QRect(80, 390, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnExit.setFont(font)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExit.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"border:2px solid rgb(55, 75, 108);\n"
"padding: 0.8em 1.5em;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 10px;\n"
"font-weight:bold;\n"
"")
        self.btnExit.setObjectName("btnExit")
        self.btnDashboard = QtWidgets.QPushButton(self.menuForm)
        self.btnDashboard.setGeometry(QtCore.QRect(80, 150, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"color: rgb(0, 0, 0);\n"
"text-align:center;\n"
"border:2px solid rgb(55, 75, 108);\n"
"padding: 0.8em 1.5em;\n"
"text-decoration: none;\n"
"font-size: 1em;\n"
"border-radius: 10px;\n"
"font-weight:bold;")
        self.btnDashboard.setObjectName("btnDashboard")
        self.namePage = QtWidgets.QLabel(self.insideForm)
        self.namePage.setGeometry(QtCore.QRect(530, 10, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.namePage.setFont(font)
        self.namePage.setStyleSheet("color: rgb(60, 91, 158);")
        self.namePage.setObjectName("namePage")
        self.comboBox = QtWidgets.QComboBox(self.insideForm)
        self.comboBox.setGeometry(QtCore.QRect(400, 131, 161, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.insideForm)
        # self.comboBox.addItem('Amad')
        self.label.setGeometry(QtCore.QRect(320, 131, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SVEdilt = QtWidgets.QLineEdit(self.insideForm)
        self.SVEdilt.setGeometry(QtCore.QRect(612, 131, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SVEdilt.setFont(font)
        self.SVEdilt.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.SVEdilt.setObjectName("SVEdilt")
        self.tableWidget = QtWidgets.QTableWidget(self.insideForm)
        self.tableWidget.setGeometry(QtCore.QRect(320, 200, 851, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.EVEdit = QtWidgets.QLineEdit(self.insideForm)
        self.EVEdit.setGeometry(QtCore.QRect(852, 132, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.EVEdit.setFont(font)
        self.EVEdit.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.EVEdit.setObjectName("EVEdit")
        self.horizontalLayout.addWidget(self.insideForm)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnScrapping.setText(_translate("Form", "Scrapping"))
        self.btnProduct.setText(_translate("Form", "Products"))
        self.btnAlgoritm.setText(_translate("Form", "Algorithm"))
        self.btnExit.setText(_translate("Form", "Exit"))
        self.btnDashboard.setText(_translate("Form", "Dashboard"))
        self.namePage.setText(_translate("Form", "Algorithm"))
        self.label.setWhatsThis(_translate("Form", "Algorithm"))
        self.label.setText(_translate("Form", "Algorithm"))
        self.SVEdilt.setPlaceholderText(_translate("Form", "   start value"))
        self.EVEdit.setPlaceholderText(_translate("Form", "   end value"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
